var handler = async (m, { conn, command }) => {
m.reply('Wait 🐦')
let audio = `https://raw.githubusercontent.com/FahriAdison/Base-Sound/main/audio/${command}.mp3`
await conn.sendFile(m.chat, audio, 'error.mp3', null, m, true)
}

handler.command = handler.help = [
'acumalaka',
'anjay',
'ara-ara',
'ara-ara-cowok',
'ara-ara2',
'arigatou',
'assalamualaikum',
'asu',
'ayank',
'aku-ngakak',
'bacot',
'bahagia-aku',
'baka',
'bansos',
'beat-box',
'beat-box2',
'biasalah',
'bidadari',
'bot',
'buka-pintu',
'canda-anjing',
'cepetan',
'cuekin-terus',
'daisuki-dayo',
'daisuki',
'dengan-mu',
'farhan-kebab',
'gaboleh-gitu',
'gak-lucu',
'gamau',
'gay',
'gelay',
'gitar',
'gomenasai',
'hai-bot',
'hampa',
'hayo',
'hp-iphone',
'i-like-you',
'ih-wibu',
'india',
'karna-lo-wibu',
'kiss',
'kontol',
'ku-coba',
'maju-wibu',
'makasih',
'mastah',
'nande-nande',
'nani',
'ngadi-ngadi',
'nikah', 'nuina',
'onichan',
'owner-sange',
'ownerku',
'pak-sapardi',
'pale',
'pantek',
'pasi-pasi',
'punten',
'sayang',
'reza-kecap',
'siapa-sih',
'siren',
'siuu',
'sudah-biasa',
'summertime',
'tanya-bapak-lu',
'to-the-bone',
'wajib',
'waku',
'woi',
'yamete',
'yowaimo',
'yoyowaimo'
]
handler.tags = ['random']
handler.owner = false
module.exports = handler
